Models/Login.cs
namespace WCE.Models  
{  
    public class Login
    {  
        private LoginStoreContext context;  
  
        public string username { get; set; }

        public string password { get;set; }
    }  
}

Models/Student.cs
namespace WCE.Models  
{  
    public class Student
    {  
        private StudentStoreContext context;

        public int stuId { get; set; }
  
        public string prn { get; set; }

        public string name { get;set; }

        public string year { get;set; }

        public string branch { get;set; }

        public string username { get;set; }

        public string password { get; set; }        
    }  
}

Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WCE.Models;

namespace WCE.Controllers  
{  
    public class LoginController : Controller     
    {  
        [HttpGet]
        public IActionResult Index()
        {
            ViewData["Message"]="Login";
            return View();
        }

        [HttpGet]
        public IActionResult Teacher()
        {
            ViewData["Message"]="Login";
            return View();
        }

        [HttpGet]
        public IActionResult Admin()
        {
            ViewData["Message"]="Login";
            return View();
        }

        [HttpPost]
        public  IActionResult Index(string username,string password)  
        {  
            LoginStoreContext context = HttpContext.RequestServices.GetService(typeof(WCE.Models.LoginStoreContext)) as LoginStoreContext;  
            string name=(string)context.AuthorizeStudent(username,password);
            if(name!="Invalid") {
                ViewData["Message"]="Valid";
                    Response.Redirect($"/Student?username={name}");   
                }
            else 
                ViewData["Message"]="Invalid Username or Password";
            return View();  
        }  

        [HttpPost]
        public  IActionResult Teacher(string username,string password)  
        {  
            LoginStoreContext context = HttpContext.RequestServices.GetService(typeof(WCE.Models.LoginStoreContext)) as LoginStoreContext;  
            string name=(string)context.AuthorizeTeacher(username,password);
            if(name!="Invalid") {
                ViewData["Message"]="Valid";
                    Response.Redirect($"/Teacher?username={name}");   
                }
            else 
                ViewData["Message"]="Invalid Username or Password";
            return View();  
        }  


         [HttpPost]
        public  IActionResult Admin(string username,string password)  
        {
            LoginStoreContext context = HttpContext.RequestServices.GetService(typeof(WCE.Models.LoginStoreContext)) as LoginStoreContext;  
            if((bool)context.AuthorizeAdmin(username,password)) {
                ViewData["Message"]="Valid";
                    Response.Redirect("/StudentData");   
                }
            else 
                ViewData["Message"]="Invalid Username or Password";
            return View();  
 
        }  
    }  
}

Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Dynamic;
using WCE.Models;

namespace WCE.Controllers  
{  
    public class StudentController : Controller  
    {  
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public void Login(string username,string password)
        {
            StudentStoreContext context = HttpContext.RequestServices.GetService(typeof(WCE.Models.StudentStoreContext)) as StudentStoreContext;
            var id=context.Login(username,password);
            Response.Redirect($"/Student/Profile/{id}");
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public void Register(string prn,string name,string year,string branch,string username,string password)
        {
            StudentStoreContext context = HttpContext.RequestServices.GetService(typeof(WCE.Models.StudentStoreContext)) as StudentStoreContext;
            context.AddStudent(prn,name,year,branch,username,password);     
            Response.Redirect("/Student/Login");
        }

        [HttpGet]
        public IActionResult Invalid()
        {
            return View();
        }

        [HttpPost]
        public void Invalid(string username,string password)
        {
            StudentStoreContext context = HttpContext.RequestServices.GetService(typeof(WCE.Models.StudentStoreContext)) as StudentStoreContext;
            var id=context.Login(username,password);
            Response.Redirect("/Student/"+id);
        }

        [HttpGet]
        public IActionResult Profile(int id)
        {
            StudentStoreContext context1 = HttpContext.RequestServices.GetService(typeof(WCE.Models.StudentStoreContext)) as StudentStoreContext;
            TestAttemptsStoreContext context2 = HttpContext.RequestServices.GetService(typeof(WCE.Models.TestAttemptsStoreContext)) as TestAttemptsStoreContext;

            ViewData["student_id"]=id;
            dynamic mymodel = new ExpandoObject();
            mymodel.Student = context1.GetStudentDetails(id);
            mymodel.TestAttempts = context2.GetTestAttemptsForStudent(id);
            return View(mymodel);
        }

        [HttpPost]
        public void Profile(int id,string name)
        {
            Response.Redirect($"/Student/EnterTest/{id}");
        }

        [HttpGet]
        public IActionResult EnterTest(int id)
        {
            TestStoreContext context = HttpContext.RequestServices.GetService(typeof(WCE.Models.TestStoreContext)) as TestStoreContext;
            dynamic mymodel = new ExpandoObject();
            mymodel.Test = context.GetAllTests();
            ViewData["id"]=id;
            return View(mymodel);
        }

        [HttpPost]
        public IActionResult EnterTest(string test_title, string test_password, int student_id){
            TestStoreContext context = HttpContext.RequestServices.GetService(typeof(WCE.Models.TestStoreContext)) as TestStoreContext;
            int test_id=context.GetTestDetails(test_title,test_password);
            if(test_id==-1){
                dynamic mymodel = new ExpandoObject();
                mymodel.Test = context.GetAllTests();
                ViewData["id"]=student_id;
                ViewData["error"]="Wrong Test Credentails";
                return View(mymodel);
            }else{
                Response.Redirect($"/Student/AttemptTest?test_id={test_id}&student_id={student_id}&question_index=1");
                return new EmptyResult();
            }
        }

        [HttpGet]
        public IActionResult AttemptTest(){
            TestStoreContext context1 = HttpContext.RequestServices.GetService(typeof(WCE.Models.TestStoreContext)) as TestStoreContext;
            QuestionStoreContext context2 = HttpContext.RequestServices.GetService(typeof(WCE.Models.QuestionStoreContext)) as QuestionStoreContext;

            int test_id = Int32.Parse(HttpContext.Request.Query["test_id"]);
            int student_id = Int32.Parse(HttpContext.Request.Query["student_id"]);
            int question_index = Int32.Parse(HttpContext.Request.Query["question_index"]);
            int last_question_index = context2.GetLastQuestionIndex(test_id);

            dynamic mymodel = new ExpandoObject();
            mymodel.Test=context1.GetTestDetails(test_id);
            mymodel.Question=context2.GetQuestion(test_id,question_index);

            ViewData["student_id"]=student_id;
            ViewData["test_id"]=test_id;
            ViewData["last_question_index"]=last_question_index;

            return View(mymodel);
        }

        [HttpPost]
        public void AttemptTest(string radio, int question_id, int test_id, int student_id, string ans, int points, int question_index, int last_question_index){
            AnswerStoreContext context1 = HttpContext.RequestServices.GetService(typeof(WCE.Models.AnswerStoreContext)) as AnswerStoreContext;

            int next_question_index=context1.SubmitAnswer(radio,question_id,test_id,student_id,ans,points,question_index);

            if(question_index!=last_question_index){
                Response.Redirect($"/Student/AttemptTest?test_id={test_id}&student_id={student_id}&question_index={next_question_index}");
            }else{
                Response.Redirect($"/Student/EndTest?test_id={test_id}&student_id={student_id}");
            }
        }

        [HttpGet]
        public IActionResult EndTest(){
            TestStoreContext context1 = HttpContext.RequestServices.GetService(typeof(WCE.Models.TestStoreContext)) as TestStoreContext;
            int test_id = Int32.Parse(HttpContext.Request.Query["test_id"]);
            int student_id = Int32.Parse(HttpContext.Request.Query["student_id"]);

            dynamic mymodel = new ExpandoObject();
            mymodel.Test=context1.GetTestDetails(test_id);

            ViewData["student_id"]=student_id;
            ViewData["test_id"]=test_id;

            return View(mymodel);
        }

        [HttpPost]
        public void EndTest(int student_id,int test_id){
            TestAttemptsStoreContext context1 = HttpContext.RequestServices.GetService(typeof(WCE.Models.TestAttemptsStoreContext)) as TestAttemptsStoreContext;
            TestStoreContext context2 = HttpContext.RequestServices.GetService(typeof(WCE.Models.TestStoreContext)) as TestStoreContext;
            StudentStoreContext context3 = HttpContext.RequestServices.GetService(typeof(WCE.Models.StudentStoreContext)) as StudentStoreContext;

            string test_title=context2.GetTestTitle(test_id);
            int total=context2.GetTotalMarks(test_id);
            string student_name=context3.GetStudentName(student_id);
            context1.EnterAttempt(student_id,test_id,total,test_title,student_name);

            Response.Redirect($"/Student/Profile/{student_id}");
        }
    }    
}

Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.Dynamic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WCE.Models;

namespace WCE.Controllers  
{  
    public class TeacherController : Controller  
    {  
        [HttpGet]
        public IActionResult Profile(int id) {
            TeacherStoreContext context = HttpContext.RequestServices.GetService(typeof(WCE.Models.TeacherStoreContext)) as TeacherStoreContext;
            dynamic mymodel = new ExpandoObject();
            mymodel.Teacher = context.getTeacherDetails(id);
            mymodel.Test= context.getTests(id);
            return View(mymodel);
        }

        [HttpPost]
        public IActionResult Profile(string type, int test_id, int teacher_id) {
            TeacherStoreContext context = HttpContext.RequestServices.GetService(typeof(WCE.Models.TeacherStoreContext)) as TeacherStoreContext;
            TestStoreContext context1 = HttpContext.RequestServices.GetService(typeof(WCE.Models.TestStoreContext)) as TestStoreContext;

            if(type=="edit"){
                var id=test_id;
                Response.Redirect($"/Question/Create/{test_id}?teacher_id={teacher_id}");
            }else{
                if(type=="delete"){
                    var id=teacher_id;
                    context.DeleteTest(test_id);
                    Response.Redirect($"/Teacher/Profile/{teacher_id}");
                }else{
                    if(type=="attempts"){
                        Response.Redirect($"/Teacher/TestAttempts?teacher_id={teacher_id}&test_id={test_id}");
                    }
                    else{
                        context1.SetTestInactive(test_id);
                        Response.Redirect($"/Teacher/Profile/{teacher_id}");
                    }
                }
            }

            dynamic mymodel = new ExpandoObject();
            mymodel.Teacher = context.getTeacherDetails(test_id);
            mymodel.Test= context.getTests(test_id);
            return View(mymodel);
        }

        [HttpGet]
        public IActionResult TestAttempts(){
            TestStoreContext context1 = HttpContext.RequestServices.GetService(typeof(WCE.Models.TestStoreContext)) as TestStoreContext;
            TestAttemptsStoreContext context2 = HttpContext.RequestServices.GetService(typeof(WCE.Models.TestAttemptsStoreContext)) as TestAttemptsStoreContext;
            dynamic mymodel = new ExpandoObject();

            int teacher_id = Int32.Parse(HttpContext.Request.Query["teacher_id"]);
            int test_id = Int32.Parse(HttpContext.Request.Query["test_id"]);

            mymodel.Test = context1.GetTestDetails(test_id);
            mymodel.TestAttempts = context2.GetTestAttemptsForTeacher(test_id);

            return View(mymodel);
        }

        [HttpGet]
        public void Create(int teacher_id) {
            TeacherStoreContext context = HttpContext.RequestServices.GetService(typeof(WCE.Models.TeacherStoreContext)) as TeacherStoreContext;
            int id=(int)context.CreateTest(teacher_id);
            Response.Redirect($"/Test/Create/{id}?teacher_id={teacher_id}");
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public void Login(string username,string password)
        {
            TeacherStoreContext context = HttpContext.RequestServices.GetService(typeof(WCE.Models.TeacherStoreContext)) as TeacherStoreContext;
            int id=(int)context.Login(username,password);
            if(id!=-1)
                Response.Redirect($"/Teacher/Profile/{id}");
            else
                ViewData["Message"]="Invalid Username or Password";
        }

        [HttpGet]
        public IActionResult Invalid()
        {
            return View();
        }

        [HttpPost]
        public void Invalid(string username,string password)
        {
            TeacherStoreContext context = HttpContext.RequestServices.GetService(typeof(WCE.Models.TeacherStoreContext)) as TeacherStoreContext;
            var id=context.Login(username,password);     
            Response.Redirect("/Teacher/"+id);
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public void Register(string name,string username,string password)
        {
            TeacherStoreContext context = HttpContext.RequestServices.GetService(typeof(WCE.Models.TeacherStoreContext)) as TeacherStoreContext;
            context.AddTeacher(name,username,password);     
            Response.Redirect("/Teacher/Login");
        }
    }    
}

Views/Student/Invalid.cshtml
@model IEnumerable<WCE.Models.Student>
@{
    ViewData["Title"]="Index";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StudentMIS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style='background-color: lightblue'>
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WCE</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        
                        <div class="dropdown">
                            <button class="btn  dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Student
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" asp-controller="Student" asp-action="Login">Login</a>
                                <a class="dropdown-item" asp-controller="Student" asp-action="Register">Register</a>
                            </div>
                        </div>
                        <div class="dropdown">
                            <button class="btn  dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Teacher
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" asp-controller="Teacher" asp-action="Login">Login</a>
                                <a class="dropdown-item" asp-controller="Teacher" asp-action="Register">Register</a>
                            </div>
                        </div>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Admin">Admin</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container card">
        <main role="main" class="pb-3 card-body">

            <h3 class='card-header'>Student Login</h3>

            <br/>
            <p class="card-text" style="color: red">Invalid Login Credantials</p>
            <br/>

            <div class="container ">

                <form method="post">
                <div class="">
                    <div class="">
                        <div class="form-group">
                            <label for="name">Enter User Name</label>
                            <input type="text" name="username" class="form-control" id="username" style="width:50%" placeholder="Enter User Name">
                        </div>
                    </div>
                    <div class="">
                        <div class="form-group">
                            <label for="name">Enter Password</label>
                            <input type="password" name="password" class="form-control" id="password" style="width:50%" placeholder="Enter Password">
                        </div>
                    </div>
                <input type="submit" class="btn btn-success" />
                </form>
            </div>
        </main>
    </div>

    <footer class="footer" style='background-color: lightblue'>
        <div class="footer-copyright text-center">
            &copy; 2021 - Online MCQ Portal - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>

Views/Student/Login.cshtml
@model IEnumerable<WCE.Models.Student>
@{
    ViewData["Title"]="Index";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StudentMIS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style='background-color: lightblue'>
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Online MCQ Platform</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        
                        <div class="dropdown">
                            <button class="btn  dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Customer
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" asp-controller="Student" asp-action="Login">Login</a>
                                <a class="dropdown-item" asp-controller="Student" asp-action="Register">Register</a>
                            </div>
                        </div>
                        <div class="dropdown">
                            <button class="btn  dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Manager
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" asp-controller="Teacher" asp-action="Login">Login</a>
                            </div>
                        </div>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container card">
        <main role="main" class="pb-3 card-body">

            <h3 class='card-header'>Student Login</h3>

            <div class="container ">

                <form method="post">
                <div class="">
                    <div class="">
                        <div class="form-group">
                            <label for="name">Enter User Name</label>
                            <input type="text" name="username" class="form-control" id="username" style="width:50%" placeholder="Enter User Name">
                        </div>
                    </div>
                    <div class="">
                        <div class="form-group">
                            <label for="name">Enter Password</label>
                            <input type="password" name="password" class="form-control" id="password" style="width:50%" placeholder="Enter Password">
                        </div>
                    </div>
                <input type="submit" class="btn btn-success" />
                </form>
            </div>
        </main>
    </div>

    <footer class="footer" style='background-color: lightblue'>
        <div class="footer-copyright text-center">
            &copy; 2021 - Online MCQ Portal - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>

Views/Student/Register.cshtml
@model IEnumerable<WCE.Models.Student>
@{
    ViewData["Title"]="Index";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StudentMIS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style='background-color: lightblue'>
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Online MCQ Platform</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        
                        <div class="dropdown">
                            <button class="btn  dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Student
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" asp-controller="Student" asp-action="Login">Login</a>
                                <a class="dropdown-item" asp-controller="Student" asp-action="Register">Register</a>
                            </div>
                        </div>
                        <div class="dropdown">
                            <button class="btn  dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Teacher
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" asp-controller="Teacher" asp-action="Login">Login</a>
                                <a class="dropdown-item" asp-controller="Teacher" asp-action="Register">Register</a>
                            </div>
                        </div>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Admin">Admin</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container card mb-3 py-3">
        <main role="main" class="card-body">

            <h3 class='card-header'>Student Register</h3>


            <div class="container ">

                <form method="post">
                <div class="">
                    <div class="">
                        <div class="form-group">
                            <label for="prn">PRN</label>
                            <input type="text" class="form-control" name="prn" id="prn" style="width:50%" placeholder="Enter PRN">
                        </div>
                    </div>
                    <div class="">
                        <div class="form-group">
                            <label for="name">Enter User Name</label>
                            <input type="text" name="username" class="form-control" id="username" style="width:50%" placeholder="Enter User Name">
                        </div>
                    </div>
                    <div class="">
                        <div class="form-group">
                            <label for="name">Enter Password</label>
                            <input type="text" name="password" class="form-control" id="password" style="width:50%" placeholder="Enter Password">
                        </div>
                    </div>
                    <div class="">
                        <div class="form-group">
                            <label for="name">Enter Name</label>
                            <input type="text" name="name" class="form-control" id="name" style="width:50%" placeholder="Enter Name">
                        </div>
                    </div>
                </div>
                
                <div class="">
                    <div class="">
                        <div class="form-group">
                            <label for="branch">Enter Branch</label>
                            <input type="text" class="form-control" style="width:50%" name="branch" id="department" placeholder="Enter Branch">
                        </div>
                    </div>
                    <div class="">
                        <div class="form-group">
                            <label for="year">Enter CurrentYear</label>
                            <input type="text" class="form-control" id="year" style="width:50%" name="year" placeholder="Enter Current Year">
                        </div>
                    </div>
                </div>
                <input type="submit" class="btn btn-success" />
                </form>
            </div>
        </main>
    </div>

    <footer class="footer" style='background-color: lightblue'>
        <div class="footer-copyright text-center">
            &copy; 2021 - Online MCQ Portal - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>